// SETTINGS CONSTANTS
export const SET_FLIGHT_NUMBER = "SET_FLIGHT_NUMBER";
export const SET_FLIGHT_DATE = "SET_FLIGHT_DATE";
export const SET_AUTH_STATUS = "SET_AUTH_STATUS";
export const SET_LUGGAGE_POPUP_STATUS = "SET_LUGGAGE_POPUP_STATUS";
export const SET_LUGGAGE_DETAIL = "SET_LUGGAGE_DETAIL";
export const SET_DELIVERY_INFO = "SET_DELIVERY_INFO";
export const ADD_LUGGAGE = "ADD_LUGGAGE";
export const ADD_ADDRESS = "ADD_ADRESS";
export const GET_FLIGHT_INFO = "GET_FLIGHT_INFO";
export const GET_FLIGHT_INFO_SUCCESS = "GET_FLIGHT_INFO_SUCCESS";
export const GET_FLIGHT_INFO_FAIL = "GET_FLIGHT_INFO_FAIL";
